function [TRANSM, YIELD] = less_transmission(YIELD, PATHFIND, METOCEAN, SCENARIO, SITES, DEVICES, IN)
%% Function Description - less_transmission - JAM 30/11/20
% This function calculates the transmission losses for the designated 
% Scenario. Currently only active losses are accounted for.

%% Inputs Description
% YIELD
% PATHFIND
% METOCEAN
% SCENARIO
% SITES
% DEVICES
% IN

%% Outputs Description
% TRANSM
% YIELD

%% DISCRETE
if IN.RUN.DISCRETE
    disp('Calculating Transmission Losses for DISCRETE Sites...'); 
    for s = 1:size(SITES,2)                                                 % For each Site...       
        % Site Name
        Start = tic; disp([' - Beginning Transmission Loss calculation for "',char(string(SITES(s).Name)),'" site...']);
        TRANSM.DISCRETE.SITES(s).Sites_Name = SITES(s).Name;
        
        % Total Distance to Landfall
        if IN.RUN.SPATIAL
            TRANSM.DISCRETE.SITES(s).Dist2LandFall_m...
                = PATHFIND.DISCRETE.SITES(s).TRANSMISSION.Path2LandFall_AStarDistance_m;
        else
            TRANSM.DISCRETE.SITES(s).Dist2LandFall_m...
                = PATHFIND.DISCRETE.SITES(s).TRANSMISSION.Path2LandFall_EuclidDistance_m;
        end
        
        for d = 1:size(DEVICES,2)                                           % For each Device... 
            % Devices Name
            disp(['     - Calculating Idealised Energy Delivered for "',DEVICES(d).Name,'" Device...']);
            TRANSM.DISCRETE.SITES(s).DEVICES(d).Devices_Name...
                = DEVICES(d).Name;
            
            %% Calculate Ideal Energy Delivered to shore (per device)                                        
           [TRANSM.DISCRETE.SITES(s).DEVICES(d).Architecture,...
            Power_IdealDel_W,...
            Power_Ideal_LossPerDevice_pc]...
                    = arrayloss(1,...                                       % Assuming each device independent.
                               (YIELD.DISCRETE.IDEAL.GENERATED.SITES(s).DEVICES(d).Power_Ideal_GenPerDevice_kW.Power_Generated_kW .* 1000),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_GenerationVoltage_V(d),... 
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_OnboardTransformerNoLoadLosses_W(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_OnboardTransformerEfficiency_pc(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_OnboardSwitchgearEfficiency_pc(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_ExportCableVoltage_V(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_ExportCableResistance_ohmpm(d),...
                                TRANSM.DISCRETE.SITES(s).Dist2LandFall_m,...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_ShoreSwitchgearEfficiency_pc(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_ShoreTransformerNoLoadLosses_W(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_ShoreTransformerEfficiency_pc(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_GridVoltage_V(d),...
                                SCENARIO.Transmission.Transmission_Parameters.Transmission_PowerFactor_pc(d),...
                                3);
                     
            TRANSM.DISCRETE.SITES(s).DEVICES(d).Power_Ideal_GenDelLossPerDevice_kW...
                = timetable(YIELD.DISCRETE.IDEAL.GENERATED.SITES(s).Flow_Vel_Abs_Surf_ms.Time,...
                            YIELD.DISCRETE.IDEAL.GENERATED.SITES(s).DEVICES(d).Power_Ideal_GenPerDevice_kW.Power_Generated_kW,...
                            Power_IdealDel_W ./ 1000,...
                            Power_Ideal_LossPerDevice_pc,...
                            'VariableNames',{'Power_Ideal_GenPerDevice_kW','Power_Ideal_DelPerDevice_kW','Power_Ideal_LossPerDevice_pc'});
            
            % Ideal Energy Generated
            TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_GenPerDevice_kWh...
                = YIELD.DISCRETE.IDEAL.GENERATED.SITES(s).DEVICES(d).Energy_Ideal_GenPerDevice_kWh;
            
            % Ideal Energy Delivered
            TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_DelPerDevice_kWh...
                = double(sum(Power_IdealDel_W ./ 1000));
            
            % Ideal Energy Loss Percentage
           [TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_LossPerDevice_kWh,...
            TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_LossPerDevice_pc]...
                = powerlossperc(YIELD.DISCRETE.IDEAL.GENERATED.SITES(s).DEVICES(d).Energy_Ideal_GenPerDevice_kWh,...
                                TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_DelPerDevice_kWh);            
            
            %% Export to YIELD Structure
            % Site & Device Name
            YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).Sites_Name...
                = SITES(s).Name;
            YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Devices_Name...
                = DEVICES(d).Name; 
 
            % Ideal Energy Generated
            YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Energy_Ideal_GenPerDevice_kWh...
                = YIELD.DISCRETE.IDEAL.GENERATED.SITES(s).DEVICES(d).Energy_Ideal_GenPerDevice_kWh;            
            
            % Ideal Energy Delivered
            YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Energy_Ideal_DelPerDevice_kWh...
               = TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_DelPerDevice_kWh;   
           
            % Ideal Energy Losses
            YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Energy_Ideal_LossPerDevice_kWh...
                = TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_LossPerDevice_kWh;
            YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Energy_Ideal_LossPerDevice_pc...
                = TRANSM.DISCRETE.SITES(s).DEVICES(d).Energy_Ideal_LossPerDevice_pc;

            %% Monthly Breakdown
            for m = 1:12                                                    % For each month... 
                % Month Name
                TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Month...
                    = monthnum2name(m,'Short');
                
                % Monthly Ideal Power Generated/Delivered/Losses Per Device
                TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Power_Ideal_GenDelLossPerDevice_kW...
                    = TRANSM.DISCRETE.SITES(s).DEVICES(d).Power_Ideal_GenDelLossPerDevice_kW(month(METOCEAN.DISCRETE.(SITES(s).Name).DateTime_UTC) == m,:);

                % Monthly Ideal Energy Generated Per Device
                TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh...
                    = double(sum(TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Power_Ideal_GenDelLossPerDevice_kW.Power_Ideal_GenPerDevice_kW));
                
                % Monthly Ideal Energy Delivered Per Device  
                TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh...
                    = double(sum(TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Power_Ideal_GenDelLossPerDevice_kW.Power_Ideal_DelPerDevice_kW));
                                  
                % Monthly Average Ideal Energy Losses   
               [TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh,...
                TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc]...
                    = powerlossperc(TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh,...
                                    TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh);
                                
                %% Export to YIELD Structure
                % Month Name
                YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Monthly(m).Month...
                    = monthnum2name(m,'Short');           

                % Monthly Ideal Energy Generated Per Device
                YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh...
                    = TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh;
                            
                % Monthly Ideal Energy Delivered Per Device 
                YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh...
                    = TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh;
                
                % Monthly Average Ideal Energy Losses 
                YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh...
                    = TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh;
                YIELD.DISCRETE.IDEAL.DELIVERED.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc...
                    = TRANSM.DISCRETE.SITES(s).DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc;
                
            end            
        end
    end
    
    % Finalise Section
    Stop = toc(Start); 
    disp([' - Time Elapsed: ',num2str(round2(Stop,0.01)),' seconds.']);
end

%% SPATIAL
if IN.RUN.SPATIAL
    disp('Calculating Transmission Losses for SPATIAL Region...');
       
    %% Preallocate NaN Arrays to be Filled
    disp(' - Preallocating memory for the population of large arrays...');
    % Valid Wet Point
    ValidChartDatumDepth_Binary...
        = logical(~PATHFIND.MAPS.BinaryMobilityMap); 

    for d = 1:size(DEVICES,2)
        % Device Name 
        TRANSM.SPATIAL.DEVICES(d).Devices_Name...
            = DEVICES(d).Name;  

        % Idealised Power Delivered
        Power_IdealDelPerDevice_W...
            = single(zeros(size(YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Power_Ideal_GenPerDevice_kW)));
        
        %% Calculate Idealised Power Delivered, Energy Delivered & Losses
        disp([' - Calculating Idealised Energy Delivered for "',DEVICES(d).Name,'" Device at every grid point (this may take some time)...']);
        Start = tic; b = waitbar(0,'1','Name','Evaluating row number...');  % Start timer.
        
        for x = 1:size(YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Power_Ideal_GenPerDevice_kW,2)                        % For each row...
            waitbar(x/size(YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Power_Ideal_GenPerDevice_kW,2), b, sprintf('%5.0f',x));
            for y = 1:size(YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Power_Ideal_GenPerDevice_kW,3)                    % For each column...
                if ValidChartDatumDepth_Binary(x,y)...                      % If the grid point is water...
                && YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).ValidDeviceDeployment_Binary(x,y)                        % If the grid point is Device specific acceptable deployment location...
                 % Idealised Power Delivered (Temporary)
                 [~,Power_IdealDelPerDevice_W(:,x,y),~]... 
                     = arrayloss(1,...
                                (YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Power_Ideal_GenPerDevice_kW(:,x,y) .* 1000),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_GenerationVoltage_V(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_OnboardTransformerNoLoadLosses_W(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_OnboardTransformerEfficiency_pc(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_OnboardSwitchgearEfficiency_pc(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_ExportCableVoltage_V(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_ExportCableResistance_ohmpm(d),...
                                 PATHFIND.SPATIAL.TRANSMISSION.Path2LandFall_AStarDistance_m(x,y),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_ShoreSwitchgearEfficiency_pc(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_ShoreTransformerNoLoadLosses_W(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_ShoreTransformerEfficiency_pc(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_GridVoltage_V(d),...
                                 SCENARIO.Transmission.Transmission_Parameters.Transmission_PowerFactor_pc(d),...
                                 3);  
                end
            end
        end
        
        Stop = toc(Start); close(b);
        disp([' - Time Elapsed: ',num2str(round2(Stop/60,0.01)),' minutes.']);
        
        %% Store Output Variables
        % Ideal Power Delivered Per Device
        TRANSM.SPATIAL.DEVICES(d).Power_Ideal_DelPerDevice_kW...
            = Power_IdealDelPerDevice_W ./ 1000; 
        clearvars Power_IdealDelPerDevice_W;
        
        % Ideal Energy Generated Per Device
        TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_GenPerDevice_kWh...
            = YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Energy_Ideal_GenPerDevice_kWh;
        
        % Ideal Energy Delivered Per Device
        TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_DelPerDevice_kWh...
            = squeeze(sum(TRANSM.SPATIAL.DEVICES(d).Power_Ideal_DelPerDevice_kW,1));
        TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_DelPerDevice_kWh(~ValidChartDatumDepth_Binary)...
            = NaN;

        % Ideal Energy Loss Per Device
       [TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_LossPerDevice_kWh,...
        TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_LossPerDevice_pc]...
            = powerlossperc(YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Energy_Ideal_GenPerDevice_kWh,...
                            TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_DelPerDevice_kWh);
                        
        %% Export to YIELD Structure
        % Device Name
        YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Devices_Name...
            = DEVICES(d).Name;  
        
        % Ideal Energy Generated Per Device
        YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Energy_Ideal_GenPerDevice_kWh...
            = YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Energy_Ideal_GenPerDevice_kWh;        
        
        % Ideal Energy Delivered Per Device
        YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Energy_Ideal_DelPerDevice_kWh...
            = TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_DelPerDevice_kWh; 
        
        % Ideal Energy Loss Per Device
        YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Energy_Ideal_LossPerDevice_kWh...
            = TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_LossPerDevice_kWh;  
        YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Energy_Ideal_LossPerDevice_pc...
            = TRANSM.SPATIAL.DEVICES(d).Energy_Ideal_LossPerDevice_pc;     
        
        %% Monthly Breakdown
        for m = 1:12                                                        % For each month...                 
            % Month Name
            TRANSM.SPATIAL.DEVICES(d).Monthly(m).Month...
                = monthnum2name(m,'Short');

            % Ideal Energy Generated Per Device
            TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh...
                = YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh;            

            % Monthly Ideal Energy Delivered Per Device
            TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh...
                = squeeze(sum(TRANSM.SPATIAL.DEVICES(d).Power_Ideal_DelPerDevice_kW(month(METOCEAN.SPATIAL.DateTime_UTC) == m,:,:),1));
            
            TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh...
                (~ValidChartDatumDepth_Binary) = NaN;

            % Monthly Ideal Energy Losses Per Device           
           [TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh,...
            TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc]...
                = powerlossperc(YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh,...
                                TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh);
                                
            TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh...
                (isnan(TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh)...
                & ValidChartDatumDepth_Binary) = 0;
            
            TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc...
                (isnan(TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc)...
                & ValidChartDatumDepth_Binary) = 0;
            
            %% Export to YIELD Structure
            % Month Name
            YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Monthly(m).Month...
                = monthnum2name(m,'Short');  
  
            % Ideal Energy Generated Per Device
            YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh...
                = YIELD.SPATIAL.IDEAL.GENERATED.DEVICES(d).Monthly(m).Energy_Ideal_GenPerDevice_kWh;               
            
            % Monthly Ideal Energy Delivered Per Device
            YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh...
                = TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_DelPerDevice_kWh;   
            
            % Monthly Ideal Energy Losses Per Device
            YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh...
                = TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_kWh;
            YIELD.SPATIAL.IDEAL.DELIVERED.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc...
                = TRANSM.SPATIAL.DEVICES(d).Monthly(m).Energy_Ideal_LossPerDevice_pc;   
            
        end 
    end
    
    % Finalise Section
    disp(' % Transmission for SPATIAL Region calculated successfully.');
end

end
