function [] = less_plots_portlabels(PATHFIND,PLOTS,PlotLabels,Legend)
%% Function Description
% This function plots the ports labels on LESS region plots.

%% Input Checks
PlotLabels = validatestring(PlotLabels,{'Full','Short','None'});
Legend = validatestring(Legend,{'On','Off'});

%% Plot Port Labels
for p = 1:size(PATHFIND.DISCRETE.PORTS,2)
    switch Legend
        case 'On'
            plot([PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_E_m],...
                 [PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_N_m],...
                 's','MarkerFaceColor',PLOTS.PortLabels_Colors{p},...
                 'MarkerEdgeColor','k',...
                 'MarkerSize',12); hold on;            
        case 'Off'
            plot([PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_E_m],...
                 [PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_N_m],...
                 's','MarkerFaceColor',PLOTS.PortLabels_Colors{p},...
                 'MarkerEdgeColor','k',...
                 'MarkerSize',12,...
                 'HandleVisibility','off'); hold on;
    end
     
    switch PlotLabels
        case 'Full'
            text(double(PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_E_m),...
                 double(PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_N_m),...
                 ['',PATHFIND.DISCRETE.PORTS(p).Ports_Name,''],...
                 'color',PLOTS.PortLabels_Colors{p},...
                 'HorizontalAlignment',PLOTS.PortLabels_HorzAlignment{p},...
                 'VerticalAlignment',  PLOTS.PortLabels_VertAlignment{p},...
                 'FontSize',PLOTS.FontSize_Legend); 
        case 'Short'
            text(double(PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_E_m),...
                 double(PATHFIND.DISCRETE.PORTS(p).ValidGridPosition_UTM_N_m),...
                 ['',PLOTS.PortLabels_Short{p},''],...
                 'color',PLOTS.PortLabels_Colors{p},...
                 'HorizontalAlignment',PLOTS.PortLabels_HorzAlignment{p},...
                 'VerticalAlignment',  PLOTS.PortLabels_VertAlignment{p},...
                 'FontSize',PLOTS.FontSize_Legend);             
    end
end

%% Legend
switch Legend
    case 'On'
        PortLegend = {PATHFIND.SPATIAL.PORTS.Ports_SizeClassification};        
        SmallMedLargeIndex = [1,4,7];
        TempLogical = false(1,size(PortLegend,2));
        TempLogical(SmallMedLargeIndex) = 1;

        for pl = 1:size(PortLegend,2)
            if ~TempLogical(pl)
                PortLegend{pl} = '';
            else
                PortLegend{pl} = [PortLegend{pl},' Port'];
            end
        end
        legend(PortLegend,'location','northeast','FontSize',PLOTS.FontSize_Legend);
end

end
