function [] = less_plots_lcoelabels(PLOTS,PlotLabels,Estimate,d)
%% Function Description
% This function plots LCoE labels on LESS region plots.

%% Input Checks
PlotLabels = validatestring(PlotLabels,{'Full','Short','None'});
Estimate = validatestring(Estimate,{'Standard','LESSMin','LESSMean','LESSMax'});

%% Plot LCoE Labels
plot(PLOTS.LCoE(d).(Estimate).UTM_EN_m(1),...
     PLOTS.LCoE(d).(Estimate).UTM_EN_m(2),...
     'o','MarkerFaceColor','None',...
     'MarkerEdgeColor',rgb('hot pink'),...
     'MarkerSize',20,...
     'LineWidth',2,...
     'HandleVisibility','off'); hold on;
 
switch PlotLabels
    case 'Full'
        plot(PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(1),...
             PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(2),...
             'o','MarkerFaceColor','None',...
             'MarkerEdgeColor',rgb('hot pink'),...
             'MarkerSize',20,...
             'LineWidth',2,...
             'HandleVisibility','off'); hold on;
         
        text(PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(1),...
             PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(2),...
             {['    Lowest LCoE in Region: ',num2bank(round2(PLOTS.LCoE(d).(Estimate).LowestInRegion,1)),' [',PLOTS.Currency,'/MWh]'],...
              ['    UTM Position [E, N]: [',num2str(round2(PLOTS.LCoE(d).(Estimate).UTM_EN_m(1)./1000,1)),', ',num2str(round2(PLOTS.LCoE(d).(Estimate).UTM_EN_m(2)./1000,1)),'] [km]']},...
             'color',rgb('black'),...
             'HorizontalAlignment','left',...
             'VerticalAlignment',  'middle',...
             'FontSize',PLOTS.FontSize_Legend);             
    case 'Short'
        plot(PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(1),...
             PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(2),...
             'o','MarkerFaceColor','None',...
             'MarkerEdgeColor',rgb('hot pink'),...
             'MarkerSize',20,...
             'LineWidth',2,...
             'HandleVisibility','off'); hold on;
         
        text(PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(1),...
             PLOTS.Axes_MarkerPlotPosition_UTM_EN_m(2),...
             {['    Lowest LCoE in Region: ',num2bank(PLOTS.LCoE(d).(Estimate).LowestInRegion),' [',PLOTS.Currency,'/MWh]']},...
             'color',rgb('black'),...
             'HorizontalAlignment','left',...
             'VerticalAlignment',  'middle',...
             'FontSize',PLOTS.FontSize_Legend);          
end

end
