%% Installation - Anchor/Foundation
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(1).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(1).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Anchor Installation at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;

%% Installation - Cable Laying
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(2).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(2).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Cable Laying Installation at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;

%% Installation - Device Connection
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(3).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(3).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Device Connection Installation at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;

%% Maintenance - Minor
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(4).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(4).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Minor Maintenance at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;

%% Maintenance - Major
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(5).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(5).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Major Maintenance at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;

%% Decommissioning - Device Disconnection
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(6).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(6).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Device Disconnection Decommissioning at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;

%% Decommissioning - Cable Retrieval
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(7).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(7).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Cable Retrieval Decommissioning at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;

%% Decommissioning - Anchor Retrieval
figure;
Device_LineTypes = {'g-','g-.',...
                    'b-','b--',...
                    'r-','r--',...
                    'm-','m--'};  

for d = [2,4,6]
    plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(8).OperationLimitedTimeOnSite.NeapAccess.NumberDaysRequiredOnSite],...
        Device_LineTypes{d},'linewidth',2); hold on;
    
        plot([OPERATIONS.DISCRETE.SITES.DEVICES(d).OPERATIONS(8).OperationLimitedTimeOnSite.NeapAccess.NumberStandbyDaysBetweenAccessPeriods],...
        Device_LineTypes{d},'linewidth',6); hold on; 

end

legend('PLATO_OnSite','PLATO_Standby',...
       'PLATI_OnSite','PLATI_Standby',...
       'HBMT_OnSite','HBMT_Standby',...
       'location','best','Interpreter', 'none');
   
set(gca,'XTick',1:12)
set(gca, 'XTickLabel',monthnum2name(get(gca,'XTick'),'Short'),...           
        'FontSize',FontSize_Axes);      
xlim([1,12]); 
ylim([0 31]);

xlabel('Month',...
   'FontSize',FontSize_Axes);
ylabel('Days Required',...
   'FontSize',FontSize_Axes);  
title({'On Site & Standby Days Required for Neap Access:',...
       'Anchor Retrieval Decommissioning at FORCE Site'},...
       'FontSize',FontSize_Axes);
set(gca, 'FontSize',FontSize_Axes);   

fig2fullscreen;
