function [] = less_plots_sitelabels(PATHFIND,PLOTS,PlotLabels)
%% Function Description
% This function plots the site labels on LESS region plots.

%% Input Checks
PlotLabels = validatestring(PlotLabels,{'Full','Short','None'});

%% Plot Site Labels
for s = 1:size(PATHFIND.DISCRETE.SITES,2)
    plot(PATHFIND.DISCRETE.SITES(s).ValidGridPosition_UTM_E_m,...
         PATHFIND.DISCRETE.SITES(s).ValidGridPosition_UTM_N_m,...
         's','MarkerFaceColor',PLOTS.SiteLabels_Colors{s},...
         'MarkerEdgeColor','k',...
         'MarkerSize',12,...
         'HandleVisibility','off'); hold on;
    switch PlotLabels
        case 'Full'
            text(double(PATHFIND.DISCRETE.SITES(s).ValidGridPosition_UTM_E_m),...
                 double(PATHFIND.DISCRETE.SITES(s).ValidGridPosition_UTM_N_m),...
                 {PATHFIND.DISCRETE.SITES(s).Sites_Name},...
                 'color',PLOTS.SiteLabels_Colors{s},...
                 'HorizontalAlignment','right',...
                 'VerticalAlignment','top',...
                 'FontSize',PLOTS.FontSize_Legend);  
        case 'Short'
            text(double(PATHFIND.DISCRETE.SITES(s).ValidGridPosition_UTM_E_m),...
                 double(PATHFIND.DISCRETE.SITES(s).ValidGridPosition_UTM_N_m),...
                 PLOTS.SiteLabels_Short{s},...
                 'color',PLOTS.SiteLabels_Colors{s},...
                 'HorizontalAlignment','left',...
                 'VerticalAlignment','bottom',...
                 'FontSize',PLOTS.FontSize_Legend);               
    end
end

end
