function [Flow_Vel_Abs_PWA_ms] = less_grid_pwa(Depth_Rounded2Bin_TimeHist_m,...
                                               BinSize_m,...
                                               Flow_Vel_Abs_DepAv_TimeHist_ms,...
                                               PowerLaw_Coefficient,...
                                               BoundaryType,...
                                               Hub2BoundaryDistance_m,...
                                               Turbines_Radius_m)
%% Function Description
%

%% Inputs Description
% Depth_Rounded2Bin_TimeHist_m

% BinSize_m

% Flow_Vel_Abs_DepAv_TimeHist_ms

% PowerLaw_Coefficient

% BoundaryType

% Hub2BoundaryDistance_m

% Turbines_Radius_m

%% Outputs Description
% Flow_Vel_Abs_PWA_ms

%% Inputs Checks
% Highly iterative script. Validating attributes will slow it down.
% validateattributes(Depth_Rounded2Bin_TimeHist_m,...
%     {'numeric'},{'column','positive','nonnan','nonempty'});
% 
% validateattributes(BinSize_m,...
%     {'numeric'},{'scalar','positive','nonnan','nonempty'});
% 
% validateattributes(Flow_Vel_Abs_DepAv_TimeHist_ms,...
%     {'numeric'},{'column','nonnegative','nonnan','nonempty'});
% 
% validateattributes(PowerLaw_Coefficient,...
%     {'numeric'},{'scalar','positive','nonnan','nonempty','<=',1});

%% Preallocate Arrays of NaNs
DepthBins_FrmBed = NaN(size(Depth_Rounded2Bin_TimeHist_m,1),...
                       size(0:BinSize_m:max(Depth_Rounded2Bin_TimeHist_m),2));   
                            
DepthBins_FrmSurf = DepthBins_FrmBed; 

BinnedVel_Profile_FrmBed = DepthBins_FrmBed;   

BinnedVel_Profile_FrmSurf = DepthBins_FrmSurf;

%% Calculate Depth Bins & Velocity Profiles (from Bed and Surface)
for t = 1:size(Depth_Rounded2Bin_TimeHist_m,1)
    Bin_Idx = size(0:BinSize_m:Depth_Rounded2Bin_TimeHist_m(t,1),2);
    
    %% Profile from Bed
    [DepthBins_FrmBed(t,1:Bin_Idx),...
     BinnedVel_Profile_FrmBed(t,1:Bin_Idx)]...
        = depav2velprofile(Flow_Vel_Abs_DepAv_TimeHist_ms(t,1),...
                           Depth_Rounded2Bin_TimeHist_m(t,1),...
                           PowerLaw_Coefficient,...
                           BinSize_m);
                       
    %% Profile from Surface
    [DepthBins_FrmSurf(t,end-Bin_Idx+1:end),...
     BinnedVel_Profile_FrmSurf(t,end-Bin_Idx+1:end)]...
        = depav2velprofile(Flow_Vel_Abs_DepAv_TimeHist_ms(t,1),...
                           Depth_Rounded2Bin_TimeHist_m(t,1),...
                           PowerLaw_Coefficient,...
                           BinSize_m);
                       
end

%% Calculate Power-Weighted Average Velocity
switch BoundaryType
    case 'Bed'
        %% Bed Devices - Swept Bin Indexes
        [Hub_BinIdx,...
         TipTop_BinIdx,...
         TipBot_BinIdx]...
            = sweptbinidx(DepthBins_FrmBed,...
                          BinSize_m,...
                          Turbines_Radius_m,...
                          Hub2BoundaryDistance_m,...
                          BoundaryType);

         %% Bed Devices - PWA             
          Flow_Vel_Abs_PWA_ms...                                            % Calculate the power-weighted average flow velocity.
                = pwa(DepthBins_FrmBed,...
                      BinnedVel_Profile_FrmBed,...
                      Turbines_Radius_m,...
                      Hub_BinIdx,...
                      TipTop_BinIdx,...
                      TipBot_BinIdx); 
                  
    case 'Surface'
         %% Bed Devices - Swept Bin Indexes
         [Hub_BinIdx,...
          TipTop_BinIdx,...
          TipBot_BinIdx]...
            = sweptbinidx(DepthBins_FrmSurf,...
                          BinSize_m,...
                          Turbines_Radius_m,...
                          Hub2BoundaryDistance_m,...
                          BoundaryType);
                  
         %% Bed Devices - PWA             
         Flow_Vel_Abs_PWA_ms...                                             % Calculate the power-weighted average flow velocity.
            = pwa(DepthBins_FrmSurf,...
                  BinnedVel_Profile_FrmSurf,...
                  Turbines_Radius_m,...
                  Hub_BinIdx,...
                  TipTop_BinIdx,...
                  TipBot_BinIdx);   
              
    otherwise
        error('"BoundaryType" must be designated by the user as "Bed" or "Surface". Check "Devices" inputs.'); 
        
end                  
                                    
end