function [DEVICES] = less_setup_devices(SCENARIO)
%% Function Description - less_setup_devices - JAM 30/11/20
% This function extracts and processes device specifc data, as defined by 
% the Scenario, in order to setup a DEVICES structure.

%% Inputs Description
% SCENARIO

%% Outputs Description
% DEVICES

%% Input Checks
disp('Setting up "Devices" data structures...');
disp(' - "Devices" data extracted successfully.');
disp(' - "Operations" data extracted successfully.');
disp(' - "Vessels" data extracted successfully.');

%% DEVICES Data Structure
DEVICES = struct([]);                                                       % Preallocate memory.
for d = 1:size(SCENARIO.Devices.Devices_TurbineArrangement,1)
    %% Name
    DEVICES(d).Name...
        = SCENARIO.Devices.Devices_TurbineArrangement.Devices_Name{d};
    
    %% Deployment Requirements
    % Anchor Points
    DEVICES(d).NumberAnchorPoints...
        = SCENARIO.Devices.Devices_DeploymentRequirements.Devices_NumberAnchorPoints(d);  
    
    % Min/Max Water Depth
    DEVICES(d).MinWaterDepth_m...
        = SCENARIO.Devices.Devices_DeploymentRequirements.Devices_MinWaterDepth_m(d);
    DEVICES(d).MaxWaterDepth_m...
        = SCENARIO.Devices.Devices_DeploymentRequirements.Devices_MaxWaterDepth_m(d);
    
    %% Turbine Arrangement
    % Turbine Name
    DEVICES(d).Turbines_Name...
        = SCENARIO.Devices.Devices_TurbineArrangement.Turbines_Name{d};
    
    % Turbine Dimensions
    DEVICES(d).Turbines_Diameter_m...
        = SCENARIO.Turbines.Turbines_Diameter.Turbines_Diameter_m...
        (strcmp(DEVICES(d).Turbines_Name, SCENARIO.Turbines.Turbines_Diameter.Turbines_Name));
    DEVICES(d).Turbines_Radius_m...
        = DEVICES(d).Turbines_Diameter_m / 2;

    % Turbine Power Performance
    DEVICES(d).PowerPerformance...
        = array2table([(0:0.1:7)',...
                       table2array(SCENARIO.Turbines.Turbines_PowerPerformance...
                                   (strcmp(DEVICES(d).Turbines_Name, SCENARIO.Turbines.Turbines_PowerPerformance.Turbines_Name),2:end))'],...
          'VariableNames',{'Flow_Vel_Abs_PWA_ms','Power_W'});
      
    % Number of Turbines  
    DEVICES(d).NumberTurbines...
        = SCENARIO.Devices.Devices_TurbineArrangement.Devices_NumberTurbines(d);
    
    % Turbine Position in the Water Column
    DEVICES(d).BoundaryType...
        = SCENARIO.Devices.Devices_TurbineArrangement.Devices_BoundaryType{d};   
    DEVICES(d).Hub2BoundaryDistance_m...
        = SCENARIO.Devices.Devices_TurbineArrangement.Devices_Hub2BoundaryDistance_m(d);

    %% Generation Limits
    DEVICES(d).GenLimit_Flow_Vel_Abs_PWA_ms...
        = SCENARIO.Devices.Devices_GenerationLimits.Flow_Vel_Abs_PWA_ms(d);
%     DEVICES(d).GenLimit_Wind_Vel_Abs_U10_ms...
%         = SCENARIO.Devices.Devices_GenerationLimits.Wind_Vel_Abs_U10_ms(d);  
    DEVICES(d).GenLimit_Wave_Hs_m...
        = SCENARIO.Devices.Devices_GenerationLimits.Wave_Hs_m(d);
    
    %% OPERATIONS Characteristics
    for o = 1:size(SCENARIO.Operations.Operations_Considered,1)
        %% Operation Name
        DEVICES(d).OPERATIONS(o).Name...
            = SCENARIO.Operations.Operations_Considered.Operations_Name{o};   
        
        %% Operations Limits
        DEVICES(d).OPERATIONS(o).OpsLimit_Flow_Vel_Abs_Surf_ms...
            = SCENARIO.Devices.Devices_OperationsLimits.Flow_Vel_Abs_Surf_ms...
              (strcmp(SCENARIO.Devices.Devices_OperationsLimits.Devices_Name,    DEVICES(d).Name)...
             & strcmp(SCENARIO.Devices.Devices_OperationsLimits.Operations_Name, DEVICES(d).OPERATIONS(o).Name));
%         DEVICES(d).OPERATIONS(o).OpsLimit_Wind_Vel_Abs_U10_ms...
%             = SCENARIO.Devices.Devices_OperationsLimits.Wind_Vel_Abs_U10_ms...
%               (strcmp(SCENARIO.Devices.Devices_OperationsLimits.Devices_Name,    DEVICES(d).Name)...
%              & strcmp(SCENARIO.Devices.Devices_OperationsLimits.Operations_Name, DEVICES(d).OPERATIONS(o).Name));
        DEVICES(d).OPERATIONS(o).OpsLimit_Wave_Hs_m...
            = SCENARIO.Devices.Devices_OperationsLimits.Wave_Hs_m...
              (strcmp(SCENARIO.Devices.Devices_OperationsLimits.Devices_Name,    DEVICES(d).Name)...
             & strcmp(SCENARIO.Devices.Devices_OperationsLimits.Operations_Name, DEVICES(d).OPERATIONS(o).Name));

        %% Operations On Site Duration
        DEVICES(d).OPERATIONS(o).OnSiteDuration_h...
            = SCENARIO.Devices.Devices_OperationsDurationsFreq.Operations_OnSiteDuration_h...
              (strcmp(SCENARIO.Devices.Devices_OperationsLimits.Devices_Name,    DEVICES(d).Name)...
             & strcmp(SCENARIO.Devices.Devices_OperationsLimits.Operations_Name, DEVICES(d).OPERATIONS(o).Name));
        
        %% Frequency of Operations
        DEVICES(d).OPERATIONS(o).FrequencyOccurence_py...
            = SCENARIO.Devices.Devices_OperationsDurationsFreq.Operations_FrequencyOccurence_py...
              (strcmp(SCENARIO.Devices.Devices_OperationsLimits.Devices_Name,    DEVICES(d).Name)...
             & strcmp(SCENARIO.Devices.Devices_OperationsLimits.Operations_Name, DEVICES(d).OPERATIONS(o).Name));
         
        %% VESSELS Suitability
        for v = 1:size(SCENARIO.Vessels.Vessels_WorkingLimits,1)
            %% Name
            DEVICES(d).OPERATIONS(o).VESSELS(v).Name...
                = SCENARIO.Vessels.Vessels_WorkingLimits.Vessels_Name{v};
            
            %% Suitability
            DEVICES(d).OPERATIONS(o).VESSELS(v).Suitability4Operation...
                = SCENARIO.Vessels.Vessels_OperationsSuitability.Vessels_Suitability...
                (strcmp(DEVICES(d).OPERATIONS(o).VESSELS(v).Name, SCENARIO.Vessels.Vessels_OperationsSuitability.Vessels_Name) ...
               & strcmp(DEVICES(d).Name,                          SCENARIO.Vessels.Vessels_OperationsSuitability.Devices_Name) ...
               & strcmp(DEVICES(d).OPERATIONS(o).Name,            SCENARIO.Vessels.Vessels_OperationsSuitability.Operations_Name));
           
            %% Vessel Size Classification
            DEVICES(d).OPERATIONS(o).VESSELS(v).Vessels_SizeClassification...
                = SCENARIO.Vessels.Vessels_SizeClassification.Vessels_SizeClassification{v};
            
            %% Transit Speed
            DEVICES(d).OPERATIONS(o).VESSELS(v).Transit_Speed_ms...
                = SCENARIO.Vessels.Vessels_WorkingLimits.Vessels_TransitSpeed_ms(v);
            
            %% Working Limits
            DEVICES(d).OPERATIONS(o).VESSELS(v).WorkingLimits_Flow_Vel_Abs_Surf_ms ...
                = SCENARIO.Vessels.Vessels_WorkingLimits.Flow_Vel_Abs_Surf_ms(v);
%             DEVICES(d).OPERATIONS(o).VESSELS(v).WorkingLimits_Wind_Vel_Abs_U10_ms...
%                 = SCENARIO.Vessels.Vessels_WorkingLimits.Wind_Vel_Abs_U10_ms(v);
            DEVICES(d).OPERATIONS(o).VESSELS(v).WorkingLimits_Wave_Hs_m...
                = SCENARIO.Vessels.Vessels_WorkingLimits.Wave_Hs_m(v);
        end
    end
end

%% Finalise
disp(' % All "Devices" data structures setup successfully.');

end
