function [Vessels_Hire_CCC,...
          Vessels_Running_CCC,...
          Vessels_Standby_CCC] = less_vesselcosts(OperationDuration_D,...
                                                  OnSiteDuration_h,...
                                                  TotalTransitTime_h,...
                                                  TotalStandbyTime_D,...
                                                  Vessels_HireCost_CCCpd,...
                                                  Vessels_RunningCost_CCCph,...
                                                  Vessels_StandbyCost_CCCpd)                       
%% Function Description - less_vesselcosts - JAM 30/11/20
% This function calculates the component costs associated with a vessel
% during marine operations.

%% Input Checks
validateattributes(OperationDuration_D,{'numeric'},...
    {'nonnegative','nonempty'});                                                   
validateattributes(OnSiteDuration_h,{'numeric'},...
    {'nonnegative','nonempty'}); 
validateattributes(TotalTransitTime_h,{'numeric'},...
    {'nonnegative','nonempty'}); 
validateattributes(TotalStandbyTime_D,{'numeric'},...
    {'nonnegative','nonempty'}); 
validateattributes(Vessels_HireCost_CCCpd,{'numeric'},...
    {'nonnegative','nonempty'}); 
validateattributes(Vessels_RunningCost_CCCph,{'numeric'},...
    {'nonnegative','nonempty'}); 
validateattributes(Vessels_StandbyCost_CCCpd,{'numeric'},...
    {'nonnegative','nonempty'}); 

%% Vessel Hire Costs
Vessels_Hire_CCC = ceil(OperationDuration_D) .* Vessels_HireCost_CCCpd;     % Round to nearest whole day.

%% Vessel Running Costs
% Assuming Burn Rate Constant Throughout Operation and Transit
% Vessels_Running_CCC...
%     = (TotalTransitTime_h + OnSiteDuration_h) .* Vessels_RunningCost_CCCph; % Account for transit time and on-site duration only.
%   
% Assuming Burn Rate Only During Transit
Vessels_Running_CCC...
    = TotalTransitTime_h .* Vessels_RunningCost_CCCph;

%% Vessel Standby Costs
Vessels_Standby_CCC = ceil(TotalStandbyTime_D) .* Vessels_StandbyCost_CCCpd;% Round to nearest whole day.           
          
%% Output Checks                
validateattributes(Vessels_Hire_CCC,{'numeric'},...
    {'nonnegative','nonempty'});                                                   
validateattributes(Vessels_Running_CCC,{'numeric'},...
    {'nonnegative','nonempty'}); 
validateattributes(Vessels_Standby_CCC,{'numeric'},...
    {'nonnegative','nonempty'});                           
                
end
